# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@mapbox/node-pre-gyp-1.0.5" = {
      name = "_at_mapbox_slash_node-pre-gyp";
      packageName = "@mapbox/node-pre-gyp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mapbox/node-pre-gyp/-/node-pre-gyp-1.0.5.tgz";
        sha512 = "4srsKPXWlIxp5Vbqz5uLfBN+du2fJChBoYn/f2h991WLdk7jUvcSk/McVLSv/X+xQIPI8eGD5GjrnygdyHnhPA==";
      };
    };
    "@types/bson-4.0.3" = {
      name = "_at_types_slash_bson";
      packageName = "@types/bson";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/bson/-/bson-4.0.3.tgz";
        sha512 = "mVRvYnTOZJz3ccpxhr3wgxVmSeiYinW+zlzQz3SXWaJmD1DuL05Jeq7nKw3SnbKmbleW5qrLG5vdyWe/A9sXhw==";
      };
    };
    "@types/mongodb-3.6.14" = {
      name = "_at_types_slash_mongodb";
      packageName = "@types/mongodb";
      version = "3.6.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mongodb/-/mongodb-3.6.14.tgz";
        sha512 = "S9WP5+rkofDjAquHNBteuPN11GDZ2vfLHvRsjLS842JgWS4aTPRj8D7QJlsBEwEXt5/JdV0x7A4800rw4cn1lg==";
      };
    };
    "@types/node-15.3.1" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "15.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-15.3.1.tgz";
        sha512 = "weaeiP4UF4XgF++3rpQhpIJWsCTS4QJw5gvBhQu6cFIxTwyxWIe3xbnrY/o2lTCQ0lsdb8YIUDUvLR4Vuz5rbw==";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "accepts-1.3.7" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.7.tgz";
        sha512 = "Il80Qs2WjYlJIBNzNkK6KYqlVMTbZLXgHx2oT0pU/fjRHyEp+PEfEPY0R3WCwAGVOtauxh1hOxNgIf5bv7dQpA==";
      };
    };
    "acorn-1.2.2" = {
      name = "acorn";
      packageName = "acorn";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz";
        sha1 = "c8ce27de0acc76d896d2b1fad3df588d9e82f014";
      };
    };
    "acorn-2.7.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-2.7.0.tgz";
        sha1 = "ab6e7d9d886aaca8b085bc3312b79a198433f0e7";
      };
    };
    "acorn-globals-1.0.9" = {
      name = "acorn-globals";
      packageName = "acorn-globals";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-globals/-/acorn-globals-1.0.9.tgz";
        sha1 = "55bb5e98691507b74579d0513413217c380c54cf";
      };
    };
    "after-0.8.2" = {
      name = "after";
      packageName = "after";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/after/-/after-0.8.2.tgz";
        sha1 = "fedb394f9f0e02aa9768e702bda23b505fae7e1f";
      };
    };
    "agent-base-6.0.2" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.2.tgz";
        sha512 = "RZNwNclF7+MS/8bDg70amg32dyeZGZxiDuQmZxKLAlQjr3jGyLx+4Kkk58UO7D2QdgFIQCovuSuZESne6RG6XQ==";
      };
    };
    "align-text-0.1.4" = {
      name = "align-text";
      packageName = "align-text";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz";
        sha1 = "0cd90a561093f35d0a99256c22b7069433fad117";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "aproba-1.2.0" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
        sha512 = "Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw==";
      };
    };
    "are-we-there-yet-1.1.5" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.5.tgz";
        sha512 = "5hYdAkZlcG8tOLujVDTgCT+uPX0VnpAH28gWsLfzpXYm7wP6mp5Q/gYyR7YQ0cKVJcXJnl3j2kpBan13PtQf6w==";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "arraybuffer.slice-0.0.6" = {
      name = "arraybuffer.slice";
      packageName = "arraybuffer.slice";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer.slice-0.0.6.tgz";
        sha1 = "f33b2159f0532a3f3107a272c0ccfbd1ad2979ca";
      };
    };
    "asap-1.0.0" = {
      name = "asap";
      packageName = "asap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-1.0.0.tgz";
        sha1 = "b2a45da5fdfa20b0496fc3768cc27c12fa916a7d";
      };
    };
    "backo2-1.0.2" = {
      name = "backo2";
      packageName = "backo2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/backo2/-/backo2-1.0.2.tgz";
        sha1 = "31ab1ac8b129363463e35b3ebb69f4dfcfba7947";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-arraybuffer-0.1.5" = {
      name = "base64-arraybuffer";
      packageName = "base64-arraybuffer";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.1.5.tgz";
        sha1 = "73926771923b5a19747ad666aa5cd4bf9c6e9ce8";
      };
    };
    "base64id-1.0.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-1.0.0.tgz";
        sha1 = "47688cb99bb6804f0e06d3e763b1c32e57d8e6b6";
      };
    };
    "bcrypt-5.0.1" = {
      name = "bcrypt";
      packageName = "bcrypt";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt/-/bcrypt-5.0.1.tgz";
        sha512 = "9BTgmrhZM2t1bNuDtrtIMVSmmxZBrJ71n8Wg+YgdjHuIWYF7SjjmCPZFB+/5i/o/PIeRpwVJR3P+NrpIItUjqw==";
      };
    };
    "better-assert-1.0.2" = {
      name = "better-assert";
      packageName = "better-assert";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/better-assert/-/better-assert-1.0.2.tgz";
        sha1 = "40866b9e1b9e0b55b481894311e68faffaebc522";
      };
    };
    "bl-2.2.1" = {
      name = "bl";
      packageName = "bl";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-2.2.1.tgz";
        sha512 = "6Pesp1w0DEX1N550i/uGV/TqucVL4AM/pgThFSN/Qq9si1/DF9aIHs1BxD8V/QU0HoeHO6cQRTAuYnLPKq1e4g==";
      };
    };
    "blob-0.0.4" = {
      name = "blob";
      packageName = "blob";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blob/-/blob-0.0.4.tgz";
        sha1 = "bcf13052ca54463f30f9fc7e95b9a47630a94921";
      };
    };
    "bluebird-3.5.1" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.1.tgz";
        sha512 = "MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA==";
      };
    };
    "body-parser-1.19.0" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.19.0.tgz";
        sha512 = "dhEPs72UPbDnAQJ9ZKMNTP6ptJaionhP5cBb541nXPlW60Jepo9RV/a4fX4XWW9CuFNK22krhrj1+rgzifNCsw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "bson-1.1.6" = {
      name = "bson";
      packageName = "bson";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bson/-/bson-1.1.6.tgz";
        sha512 = "EvVNVeGo4tHxwi8L6bPj3y3itEvStdwvvlojVxxbyYfoaxJ6keLgrTuKdyfEAszFK+H3olzBuafE0yoh0D1gdg==";
      };
    };
    "bytes-3.1.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.1.0.tgz";
        sha512 = "zauLjrfCG+xvoyaqLoV8bLVXXNGC4JqlxFCutSDWA6fJrTo2ZuvLYTqZ7aHBLZSMOopbzwv8f+wZcVzfVTI2Dg==";
      };
    };
    "callsite-1.0.0" = {
      name = "callsite";
      packageName = "callsite";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz";
        sha1 = "280398e5d664bd74038b6f0905153e6e8af1bc20";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "center-align-0.1.3" = {
      name = "center-align";
      packageName = "center-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/center-align/-/center-align-0.1.3.tgz";
        sha1 = "aa0d32629b6ee972200411cbd4461c907bc2b7ad";
      };
    };
    "character-parser-1.2.1" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-1.2.1.tgz";
        sha1 = "c0dde4ab182713b919b970959a123ecc1a30fcd6";
      };
    };
    "chownr-2.0.0" = {
      name = "chownr";
      packageName = "chownr";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
        sha512 = "bIomtDF5KGpdogkLd9VspvFzk9KfpyyGlS8YFVZl7TGPBHL5snIOnxeshwVgPteQ9b4Eydl+pVbIyE1DcvCWgQ==";
      };
    };
    "clean-css-3.4.28" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "3.4.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-3.4.28.tgz";
        sha1 = "bf1945e82fc808f55695e6ddeaec01400efd03ff";
      };
    };
    "cliui-2.1.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-2.1.0.tgz";
        sha1 = "4b475760ff80264c762c3a1719032e91c7fea0d1";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "commander-2.6.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.6.0.tgz";
        sha1 = "9df7e52fb2a0cb0fb89058ee80c3104225f37e1d";
      };
    };
    "commander-2.8.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.8.1.tgz";
        sha1 = "06be367febfda0c330aa1e2a072d3dc9762425d4";
      };
    };
    "component-bind-1.0.0" = {
      name = "component-bind";
      packageName = "component-bind";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-bind/-/component-bind-1.0.0.tgz";
        sha1 = "00c608ab7dcd93897c0009651b1d3a8e1e73bbd1";
      };
    };
    "component-emitter-1.1.2" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.1.2.tgz";
        sha1 = "296594f2753daa63996d2af08d15a95116c9aec3";
      };
    };
    "component-emitter-1.2.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.2.1.tgz";
        sha1 = "137918d6d78283f7df7a6b7c5a63e140e69425e6";
      };
    };
    "component-inherit-0.0.3" = {
      name = "component-inherit";
      packageName = "component-inherit";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-inherit/-/component-inherit-0.0.3.tgz";
        sha1 = "645fc4adf58b72b649d5cae65135619db26ff143";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "connect-flash-0.1.1" = {
      name = "connect-flash";
      packageName = "connect-flash";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect-flash/-/connect-flash-0.1.1.tgz";
        sha1 = "d8630f26d95a7f851f9956b1e8cc6732f3b6aa30";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "constantinople-3.0.2" = {
      name = "constantinople";
      packageName = "constantinople";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/constantinople/-/constantinople-3.0.2.tgz";
        sha1 = "4b945d9937907bcd98ee575122c3817516544141";
      };
    };
    "content-disposition-0.5.3" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.3.tgz";
        sha512 = "ExO0774ikEObIAEV9kDo50o+79VCUdEB6n6lzKgGwupcVeRlhrj3qGAfwq8G6uBJjkqLrhT0qEYFcWng8z1z0g==";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.1.3" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.3.tgz";
        sha1 = "e734a5c1417fce472d5aef82c381cabb64d1a435";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-0.4.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.0.tgz";
        sha512 = "+Hp8fLp57wnUSt0tY0tHEXh4voZRDnoIrZPqlo3DPiI4y9lwg/jqx+1Om94/W6ZaPDOUbnjOt/99w66zk+l1Xg==";
      };
    };
    "cookie-0.4.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.1.tgz";
        sha512 = "ZwrFkGJxUR3EIoXtO+yVE69Eb7KlixbaeAWfBQB9vVsNn/o+Yw69gBWSSDK825hQNdN+wF8zELf3dFNl/kxkUA==";
      };
    };
    "cookie-parser-1.3.5" = {
      name = "cookie-parser";
      packageName = "cookie-parser";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-parser/-/cookie-parser-1.3.5.tgz";
        sha1 = "9d755570fb5d17890771227a02314d9be7cf8356";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "css-1.0.8" = {
      name = "css";
      packageName = "css";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/css/-/css-1.0.8.tgz";
        sha1 = "9386811ca82bccc9ee7fb5a732b1e2a317c8a3e7";
      };
    };
    "css-parse-1.0.4" = {
      name = "css-parse";
      packageName = "css-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-parse/-/css-parse-1.0.4.tgz";
        sha1 = "38b0503fbf9da9f54e9c1dbda60e145c77117bdd";
      };
    };
    "css-stringify-1.0.5" = {
      name = "css-stringify";
      packageName = "css-stringify";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-stringify/-/css-stringify-1.0.5.tgz";
        sha1 = "b0d042946db2953bb9d292900a6cb5f6d0122031";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "debug-2.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.3.3.tgz";
        sha1 = "40c453e67e6e13c901ddec317af8986cda9eff8c";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "denque-1.5.0" = {
      name = "denque";
      packageName = "denque";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-1.5.0.tgz";
        sha512 = "CYiCSgIF1p6EUByQPlGkKnP1M9g0ZV3qMIrqMqZqdwazygIA/YP2vrbcyl1h/WppKJTdl1F85cXIle+394iDAQ==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "detect-libc-1.0.3" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-1.0.3.tgz";
        sha1 = "fa137c4bd698edf55cd5cd02ac559f91a4c4ba9b";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "engine.io-1.8.5" = {
      name = "engine.io";
      packageName = "engine.io";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io/-/engine.io-1.8.5.tgz";
        sha512 = "j1DWIcktw4hRwrv6nWx++5nFH2X64x16MAG2P0Lmi5Dvdfi3I+Jhc7JKJIdAmDJa+5aZ/imHV7dWRPy2Cqjh3A==";
      };
    };
    "engine.io-client-1.8.5" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "1.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-1.8.5.tgz";
        sha512 = "AYTgHyeVUPitsseqjoedjhYJapNVoSPShbZ+tEUX9/73jgZ/Z3sUlJf9oYgdEBBdVhupUpUqSxH0kBCXlQnmZg==";
      };
    };
    "engine.io-parser-1.3.2" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-1.3.2.tgz";
        sha1 = "937b079f0007d0893ec56d46cb220b8cb435220a";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "express-4.17.1" = {
      name = "express";
      packageName = "express";
      version = "4.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.17.1.tgz";
        sha512 = "mHJ9O79RqluphRrcw2X/GTh3k9tVv8YcoyY4Kkh4WDMUYKRZUq0h1o0w2rrrxBqM7VoeUVqgb27xlEMXTnYt4g==";
      };
    };
    "express-session-1.17.2" = {
      name = "express-session";
      packageName = "express-session";
      version = "1.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express-session/-/express-session-1.17.2.tgz";
        sha512 = "mPcYcLA0lvh7D4Oqr5aNJFMtBMKPLl++OKKxkHzZ0U0oDq1rpKBnkR5f5vCHR26VeArlTOEF9td4x5IjICksRQ==";
      };
    };
    "finalhandler-1.1.2" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.2.tgz";
        sha512 = "aAWcW57uxVNrQZqFXjITpW3sIUQmHGG3qSb9mUah9MgMC4NeWhNOlNjXEYq3HjRAvL6arUviZGGJsBg6z0zsWA==";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "fs-minipass-2.1.0" = {
      name = "fs-minipass";
      packageName = "fs-minipass";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
        sha512 = "V/JgOLFCS+R6Vcq0slCuaeWEdNC3ouDlJMNIsacH2VtALiu9mV4LPrHc5cDl8k5aw6J8jwgWWpiTo5RYhmIzvg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "gauge-2.7.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "2c03405c7538c39d7eb37b317022e325fb018bf7";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "has-binary-0.1.7" = {
      name = "has-binary";
      packageName = "has-binary";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-binary/-/has-binary-0.1.7.tgz";
        sha1 = "68e61eb16210c9545a0a5cce06a873912fe1e68c";
      };
    };
    "has-cors-1.1.0" = {
      name = "has-cors";
      packageName = "has-cors";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-cors/-/has-cors-1.1.0.tgz";
        sha1 = "5e474793f7ea9843d1bb99c23eef49ff126fff39";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "http-errors-1.7.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.2.tgz";
        sha512 = "uUQBt3H/cSIVfch6i1EuPNy/YsRSOUBXTVfZ+yR7Zjez3qjBz6i9+i4zjNaoqcoFVI4lQJ5plg63TvGfRSDCRg==";
      };
    };
    "https-proxy-agent-5.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz";
        sha512 = "EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "is-promise-1.0.1" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-1.0.1.tgz";
        sha1 = "31573761c057e33c2e91aab9e96da08cefbe76e5";
      };
    };
    "is-promise-2.2.2" = {
      name = "is-promise";
      packageName = "is-promise";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-promise/-/is-promise-2.2.2.tgz";
        sha512 = "+lP4/6lKUBfQjZ2pdxThZvLUAafmZb8OAxFb8XXtiQmS35INgr85hdOGoEs124ez1FCnZJt6jau/T+alh58QFQ==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "jade-1.11.0" = {
      name = "jade";
      packageName = "jade";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jade/-/jade-1.11.0.tgz";
        sha1 = "9c80e538c12d3fb95c8d9bb9559fa0cc040405fd";
      };
    };
    "json3-3.3.2" = {
      name = "json3";
      packageName = "json3";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json3/-/json3-3.3.2.tgz";
        sha1 = "3c0434743df93e2f5c42aee7b19bcb483575f4e1";
      };
    };
    "jstransformer-0.0.2" = {
      name = "jstransformer";
      packageName = "jstransformer";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstransformer/-/jstransformer-0.0.2.tgz";
        sha1 = "7aae29a903d196cfa0973d885d3e47947ecd76ab";
      };
    };
    "kareem-2.3.2" = {
      name = "kareem";
      packageName = "kareem";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kareem/-/kareem-2.3.2.tgz";
        sha512 = "STHz9P7X2L4Kwn72fA4rGyqyXdmrMSdxqHx9IXon/FXluXieaFA6KJ2upcHAHxQPQ0LeM/OjLrhFxifHewOALQ==";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "lazy-cache-1.0.4" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz";
        sha1 = "a1d78fc3a50474cb80845d3b3b6e1da49a446e8e";
      };
    };
    "longest-1.0.1" = {
      name = "longest";
      packageName = "longest";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest/-/longest-1.0.1.tgz";
        sha1 = "30a0b2da38f73770e8294a0d22e6625ed77d0097";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "make-dir-3.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.1.0.tgz";
        sha512 = "g3FeP20LNwhALb/6Cz6Dd4F2ngze0jz7tbzrD2wAV+o9FeNHe4rL+yK2md0J/fiSf1sa1ADhXqi5+oVwOM/eGw==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "memory-pager-1.5.0" = {
      name = "memory-pager";
      packageName = "memory-pager";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-pager/-/memory-pager-1.5.0.tgz";
        sha512 = "ZS4Bp4r/Zoeq6+NLJpP+0Zzm0pR8whtGPf1XExKLJBAczGMnSi3It14OiNCStjQjM6NU1okjQGSxgEZN8eBYKg==";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.47.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.47.0.tgz";
        sha512 = "QBmA/G2y+IfeS4oktet3qRZ+P5kPhCKRXxXnQEudYqUaEioAU1/Lq2us3D/t1Jfo4hE9REQPrbB7K5sOczJVIw==";
      };
    };
    "mime-types-2.1.30" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.30.tgz";
        sha512 = "crmjA4bLtR8m9qLpHvgxSChT+XoSlZi8J4n/aIdn3z92e/U47Z0V/yl+Wh9W046GgFVAmoNR/fmdbZYcSSIUeg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "minipass-3.1.3" = {
      name = "minipass";
      packageName = "minipass";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-3.1.3.tgz";
        sha512 = "Mgd2GdMVzY+x3IJ+oHnVM+KG3lA5c8tnabyJKmHSaG2kAGpudxuOf8ToDkhumF7UzME7DecbQE9uOZhNm7PuJg==";
      };
    };
    "minizlib-2.1.2" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
        sha512 = "bAxsR8BVfj60DWXHE3u30oHzfl4G7khkSuPW+qvpd7jFRHm7dLxOjUk1EHACJ/hxLY8phGJ0YhYHZo7jil7Qdg==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "mongodb-3.6.6" = {
      name = "mongodb";
      packageName = "mongodb";
      version = "3.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongodb/-/mongodb-3.6.6.tgz";
        sha512 = "WlirMiuV1UPbej5JeCMqE93JRfZ/ZzqE7nJTwP85XzjAF4rRSeq2bGCb1cjfoHLOF06+HxADaPGqT0g3SbVT1w==";
      };
    };
    "mongoose-5.12.10" = {
      name = "mongoose";
      packageName = "mongoose";
      version = "5.12.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongoose/-/mongoose-5.12.10.tgz";
        sha512 = "/VmFFEACH2yiuPcJoBjOzVTXozBhCeminVbWI8mxiZwvgCbNu9PQrIABIgeCJncnZH8VT4G7s2IXO5FySxF1XA==";
      };
    };
    "mongoose-legacy-pluralize-1.0.2" = {
      name = "mongoose-legacy-pluralize";
      packageName = "mongoose-legacy-pluralize";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mongoose-legacy-pluralize/-/mongoose-legacy-pluralize-1.0.2.tgz";
        sha512 = "Yo/7qQU4/EyIS8YDFSeenIvXxZN+ld7YdV9LqFVQJzTLye8unujAWPZ4NWKfFA+RNjh+wvTWKY9Z3E5XM6ZZiQ==";
      };
    };
    "mpath-0.8.3" = {
      name = "mpath";
      packageName = "mpath";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mpath/-/mpath-0.8.3.tgz";
        sha512 = "eb9rRvhDltXVNL6Fxd2zM9D4vKBxjVVQNLNijlj7uoXUy19zNDsIif5zR+pWmPCWNKwAtqyo4JveQm4nfD5+eA==";
      };
    };
    "mquery-3.2.5" = {
      name = "mquery";
      packageName = "mquery";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mquery/-/mquery-3.2.5.tgz";
        sha512 = "VjOKHHgU84wij7IUoZzFRU07IAxd5kWJaDmyUzQlbjHjyoeK5TNeeo8ZsFDtTYnSgpW6n/nMNIHvE3u8Lbrf4A==";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "negotiator-0.6.2" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.2.tgz";
        sha512 = "hZXc7K2e+PgeI1eDBe/10Ard4ekbfrrqG8Ep+8Jmf4JID2bNg7NvCPOZN+kfF574pFQI7mum2AUqDidoKqcTOw==";
      };
    };
    "node-addon-api-3.2.0" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-3.2.0.tgz";
        sha512 = "kcwSAWhPi4+QzAtsL2+2s/awvDo2GKLsvMCwNRxb5BUshteXU8U97NCyvQDsGKs/m0He9WcG4YWew/BnuLx++w==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "nopt-5.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-5.0.0.tgz";
        sha512 = "Tbj67rffqceeLpcRXrT7vKAN8CwfPeIBgM7E6iBkmKLV7bEMwpGgYLGv0jACUsECaa/vuxP0IjEont6umdMgtQ==";
      };
    };
    "npmlog-4.1.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
        sha512 = "2uUqazuKlTaSI/dC8AzicUck7+IrEaOnN/e0jd3Xtt1KcGpwx30v50mL7oPyr/h9bL3E4aZccVwpwP+5W9Vjkg==";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-component-0.0.3" = {
      name = "object-component";
      packageName = "object-component";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-component/-/object-component-0.0.3.tgz";
        sha1 = "f0c69aa50efc95b866c186f400a33769cb2f1291";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "on-headers-1.0.2" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.2.tgz";
        sha512 = "pZAE+FJLoyITytdqK0U5s+FIpjN0JP3OzFi/u8Rx+EV5/W+JTWGXG8xFzevE7AjBfDqHv/8vL8qQsIhHnqRkrA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optimist-0.3.7" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz";
        sha1 = "c90941ad59e4273328923074d2cf2e7cbc6ec0d9";
      };
    };
    "optional-require-1.0.3" = {
      name = "optional-require";
      packageName = "optional-require";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/optional-require/-/optional-require-1.0.3.tgz";
        sha512 = "RV2Zp2MY2aeYK5G+B/Sps8lW5NHAzE5QClbFP15j+PWmP+T9PxlJXBOOLoSAdgwFvS4t0aMR4vpedMkbHfh0nA==";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "parsejson-0.0.3" = {
      name = "parsejson";
      packageName = "parsejson";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parsejson/-/parsejson-0.0.3.tgz";
        sha1 = "ab7e3759f209ece99437973f7d0f1f64ae0e64ab";
      };
    };
    "parseqs-0.0.5" = {
      name = "parseqs";
      packageName = "parseqs";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseqs/-/parseqs-0.0.5.tgz";
        sha1 = "d5208a3738e46766e291ba2ea173684921a8b89d";
      };
    };
    "parseuri-0.0.5" = {
      name = "parseuri";
      packageName = "parseuri";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseuri/-/parseuri-0.0.5.tgz";
        sha1 = "80204a50d4dbb779bfdc6ebe2778d90e4bce320a";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "passport-0.4.1" = {
      name = "passport";
      packageName = "passport";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport/-/passport-0.4.1.tgz";
        sha512 = "IxXgZZs8d7uFSt3eqNjM9NQ3g3uQCW5avD8mRNoXV99Yig50vjuaez6dQK2qC0kVWPRTujxY0dWgGfT09adjYg==";
      };
    };
    "passport-local-1.0.0" = {
      name = "passport-local";
      packageName = "passport-local";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport-local/-/passport-local-1.0.0.tgz";
        sha1 = "1fe63268c92e75606626437e3b906662c15ba6ee";
      };
    };
    "passport-strategy-1.0.0" = {
      name = "passport-strategy";
      packageName = "passport-strategy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/passport-strategy/-/passport-strategy-1.0.0.tgz";
        sha1 = "b5539aa8fc225a3d1ad179476ddf236b440f52e4";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "pause-0.0.1" = {
      name = "pause";
      packageName = "pause";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause/-/pause-0.0.1.tgz";
        sha1 = "1d408b3fdb76923b9543d96fb4c9dfd535d9cb5d";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "promise-2.0.0" = {
      name = "promise";
      packageName = "promise";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-2.0.0.tgz";
        sha1 = "46648aa9d605af5d2e70c3024bf59436da02b80e";
      };
    };
    "promise-6.1.0" = {
      name = "promise";
      packageName = "promise";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-6.1.0.tgz";
        sha1 = "2ce729f6b94b45c26891ad0602c5c90e04c6eef6";
      };
    };
    "proxy-addr-2.0.6" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.6.tgz";
        sha512 = "dh/frvCBVmSsDYzw6n926jv974gddhkFPfiN8hPOi30Wax25QZyZEGveluCgliBnqmuM+UJmBErbAUFIoDbjOw==";
      };
    };
    "qs-6.7.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.7.0.tgz";
        sha512 = "VCdBRNFTX1fyE7Nb6FYoURo/SPe62QCaAyzJvUjwRaIsc+NePBEniHlvxFmmX56+HZphIGtV0XeCirBtpDrTyQ==";
      };
    };
    "random-bytes-1.0.0" = {
      name = "random-bytes";
      packageName = "random-bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-bytes/-/random-bytes-1.0.0.tgz";
        sha1 = "4f68a1dc0ae58bd3fb95848c30324db75d64360b";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "raw-body-2.4.0" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.4.0.tgz";
        sha512 = "4Oz8DUIwdvoa5qMJelxipzi/iJIi40O5cGV1wNYp5hvZP8ZN0T+jiNkL0QepXs+EsQ9XJ8ipEDoiH70ySUJP3Q==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "regexp-clone-1.0.0" = {
      name = "regexp-clone";
      packageName = "regexp-clone";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp-clone/-/regexp-clone-1.0.0.tgz";
        sha512 = "TuAasHQNamyyJ2hb97IuBEif4qBHGjPHBS64sZwytpLEqtBQ1gPJTnOaQ6qmpET16cK14kkjbazl6+p0RRv0yw==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "right-align-0.1.3" = {
      name = "right-align";
      packageName = "right-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz";
        sha1 = "61339b722fe6a3515689210d24e14c96148613ef";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "saslprep-1.0.3" = {
      name = "saslprep";
      packageName = "saslprep";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/saslprep/-/saslprep-1.0.3.tgz";
        sha512 = "/MY/PEMbk2SuY5sScONwhUDsV2p77Znkb/q3nSVstq/yQzYJOH/Azh29p9oJLsl3LnQwSvZDKagDGBsBwSooag==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "semver-7.3.5" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.5.tgz";
        sha512 = "PoeGJYh8HK4BTO/a9Tf6ZG3veo/A7ZVsYrSA6J8ny9nb3B1VrpkuN+z9OE5wfE5p6H4LchYZsegiQgbJD94ZFQ==";
      };
    };
    "send-0.17.1" = {
      name = "send";
      packageName = "send";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.17.1.tgz";
        sha512 = "BsVKsiGcQMFwT8UxypobUKyv7irCNRHk1T0G680vk88yf6LBByGcZJOTJCrTP2xVN6yI+XjPJcNuE3V4fT9sAg==";
      };
    };
    "serve-static-1.14.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.14.1.tgz";
        sha512 = "JMrvUwE54emCYWlTI+hGrGv5I8dEwmco/00EvkzIIsR7MqrHonbD9pO2MOfFnpFntl7ecpZs+3mW+XbQZu9QCg==";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "setprototypeof-1.1.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz";
        sha512 = "JvdAWfbXeIGaZ9cILp38HntZSFSo3mWg6xGcJJsd+d4aRMOqauag1C63dJfDw7OaMYwEbHMOxEZ1lqVRYP2OAw==";
      };
    };
    "sift-13.5.2" = {
      name = "sift";
      packageName = "sift";
      version = "13.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sift/-/sift-13.5.2.tgz";
        sha512 = "+gxdEOMA2J+AI+fVsCqeNn7Tgx3M9ZN9jdi95939l1IJ8cZsqS8sqpJyOkic2SJk+1+98Uwryt/gL6XDaV+UZA==";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "sliced-1.0.1" = {
      name = "sliced";
      packageName = "sliced";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sliced/-/sliced-1.0.1.tgz";
        sha1 = "0b3a662b5d04c3177b1926bea82b03f837a2ef41";
      };
    };
    "socket.io-1.7.4" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-1.7.4.tgz";
        sha1 = "2f7ecedc3391bf2d5c73e291fe233e6e34d4dd00";
      };
    };
    "socket.io-adapter-0.5.0" = {
      name = "socket.io-adapter";
      packageName = "socket.io-adapter";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-0.5.0.tgz";
        sha1 = "cb6d4bb8bec81e1078b99677f9ced0046066bb8b";
      };
    };
    "socket.io-client-1.7.4" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-1.7.4.tgz";
        sha1 = "ec9f820356ed99ef6d357f0756d648717bdd4281";
      };
    };
    "socket.io-parser-2.3.1" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.3.1.tgz";
        sha1 = "dd532025103ce429697326befd64005fcfe5b4a0";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha1 = "c24bc146ca517c1471f5dacbe2571b2b7f9e3346";
      };
    };
    "source-map-0.4.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.4.4.tgz";
        sha1 = "eba4f5da9c0dc999de68032d8b4f76173652036b";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "sparse-bitfield-3.0.3" = {
      name = "sparse-bitfield";
      packageName = "sparse-bitfield";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sparse-bitfield/-/sparse-bitfield-3.0.3.tgz";
        sha1 = "ff4ae6e68656056ba4b3e792ab3334d38273ca11";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "tar-6.1.0" = {
      name = "tar";
      packageName = "tar";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-6.1.0.tgz";
        sha512 = "DUCttfhsnLCjwoDoFcI+B2iJgYa93vBnDUATYEeRx6sntCTdN01VnqsIuTlALXla/LWooNg0yEGeB+Y8WdFxGA==";
      };
    };
    "to-array-0.1.4" = {
      name = "to-array";
      packageName = "to-array";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-array/-/to-array-0.1.4.tgz";
        sha1 = "17e6c11f73dd4f3d74cda7a4ff3238e9ad9bf890";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "transformers-2.1.0" = {
      name = "transformers";
      packageName = "transformers";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/transformers/-/transformers-2.1.0.tgz";
        sha1 = "5d23cb35561dd85dc67fb8482309b47d53cce9a7";
      };
    };
    "type-is-1.6.18" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.18.tgz";
        sha512 = "TkRKr9sUTxEH8MdfuCSP7VizJyzRNMjj2J2do2Jr3Kym598JVdEksuzPQCnlFPW4ky9Q+iA+ma9BGm06XQBy8g==";
      };
    };
    "uglify-js-2.2.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz";
        sha1 = "a6e02a70d839792b9780488b7b8b184c095c99c7";
      };
    };
    "uglify-js-2.8.29" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.8.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz";
        sha1 = "29c5733148057bb4e1f75df35b7a9cb72e6a59dd";
      };
    };
    "uglify-to-browserify-1.0.2" = {
      name = "uglify-to-browserify";
      packageName = "uglify-to-browserify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz";
        sha1 = "6e0924d6bda6b5afe349e39a6d632850a0f882b7";
      };
    };
    "uid-safe-2.1.5" = {
      name = "uid-safe";
      packageName = "uid-safe";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-safe/-/uid-safe-2.1.5.tgz";
        sha512 = "KPHm4VL5dDXKz01UuEd88Df+KzynaohSL9fBh096KWAxSKZQDI2uBrVqtvRM4rwrIrRRKsdLNML/lnaaVSRioA==";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "void-elements-2.0.1" = {
      name = "void-elements";
      packageName = "void-elements";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/void-elements/-/void-elements-2.0.1.tgz";
        sha1 = "c066afb582bb1cb4128d60ea92392e94d5e9dbec";
      };
    };
    "wide-align-1.1.3" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.3.tgz";
        sha512 = "QGkOQc8XL6Bt5PwnsExKBPuMKBxnGxWWW3fU55Xt4feHozMUhdUMaBCk290qpm/wG5u/RSKzwdAC4i51YigihA==";
      };
    };
    "window-size-0.1.0" = {
      name = "window-size";
      packageName = "window-size";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz";
        sha1 = "5438cd2ea93b202efa3a19fe8887aee7c94f9c9d";
      };
    };
    "with-4.0.3" = {
      name = "with";
      packageName = "with";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/with/-/with-4.0.3.tgz";
        sha1 = "eefd154e9e79d2c8d3417b647a8f14d9fecce14e";
      };
    };
    "wordwrap-0.0.2" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz";
        sha1 = "b79669bb42ecb409f83d583cad52ca17eaa1643f";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-1.1.5" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.5.tgz";
        sha512 = "o3KqipXNUdS7wpQzBHSe180lBGO60SoK0yVo3CYJgb2MkobuWuBX6dhkYP5ORCLd55y+SaflMOV5fqAB53ux4w==";
      };
    };
    "wtf-8-1.0.0" = {
      name = "wtf-8";
      packageName = "wtf-8";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wtf-8/-/wtf-8-1.0.0.tgz";
        sha1 = "392d8ba2d0f1c34d1ee2d630f15d0efb68e1048a";
      };
    };
    "xmlhttprequest-ssl-1.5.3" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-1.5.3.tgz";
        sha1 = "185a888c04eca46c3e4070d99f7b49de3528992d";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-3.10.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "3.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz";
        sha1 = "f7ee7bd857dd7c1d2d38c0e74efbd681d1431fd1";
      };
    };
    "yeast-0.1.2" = {
      name = "yeast";
      packageName = "yeast";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz";
        sha1 = "008e06d8094320c372dbc2f8ed76a0ca6c8ac419";
      };
    };
  };
  args = {
    name = "fairy-chess";
    packageName = "fairy-chess";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@mapbox/node-pre-gyp-1.0.5"
      sources."@types/bson-4.0.3"
      sources."@types/mongodb-3.6.14"
      sources."@types/node-15.3.1"
      sources."abbrev-1.1.1"
      sources."accepts-1.3.7"
      sources."acorn-2.7.0"
      sources."acorn-globals-1.0.9"
      sources."after-0.8.2"
      sources."agent-base-6.0.2"
      sources."align-text-0.1.4"
      sources."amdefine-1.0.1"
      sources."ansi-regex-2.1.1"
      sources."aproba-1.2.0"
      sources."are-we-there-yet-1.1.5"
      sources."array-flatten-1.1.1"
      sources."arraybuffer.slice-0.0.6"
      sources."asap-1.0.0"
      sources."backo2-1.0.2"
      sources."balanced-match-1.0.2"
      sources."base64-arraybuffer-0.1.5"
      sources."base64id-1.0.0"
      sources."bcrypt-5.0.1"
      sources."better-assert-1.0.2"
      sources."bl-2.2.1"
      sources."blob-0.0.4"
      sources."bluebird-3.5.1"
      (sources."body-parser-1.19.0" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      sources."brace-expansion-1.1.11"
      sources."bson-1.1.6"
      sources."bytes-3.1.0"
      sources."callsite-1.0.0"
      sources."camelcase-1.2.1"
      sources."center-align-0.1.3"
      sources."character-parser-1.2.1"
      sources."chownr-2.0.0"
      (sources."clean-css-3.4.28" // {
        dependencies = [
          sources."commander-2.8.1"
        ];
      })
      (sources."cliui-2.1.0" // {
        dependencies = [
          sources."wordwrap-0.0.2"
        ];
      })
      sources."code-point-at-1.1.0"
      sources."commander-2.6.0"
      sources."component-bind-1.0.0"
      sources."component-emitter-1.2.1"
      sources."component-inherit-0.0.3"
      sources."concat-map-0.0.1"
      sources."connect-flash-0.1.1"
      sources."console-control-strings-1.1.0"
      sources."constantinople-3.0.2"
      sources."content-disposition-0.5.3"
      sources."content-type-1.0.4"
      sources."cookie-0.1.3"
      sources."cookie-parser-1.3.5"
      sources."cookie-signature-1.0.6"
      sources."core-util-is-1.0.2"
      sources."css-1.0.8"
      sources."css-parse-1.0.4"
      sources."css-stringify-1.0.5"
      sources."debug-4.3.2"
      sources."decamelize-1.2.0"
      sources."delegates-1.0.0"
      sources."denque-1.5.0"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      sources."detect-libc-1.0.3"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      (sources."engine.io-1.8.5" // {
        dependencies = [
          sources."accepts-1.3.3"
          sources."cookie-0.3.1"
          sources."debug-2.3.3"
          sources."ms-0.7.2"
          sources."negotiator-0.6.1"
        ];
      })
      (sources."engine.io-client-1.8.5" // {
        dependencies = [
          sources."debug-2.3.3"
          sources."ms-0.7.2"
        ];
      })
      sources."engine.io-parser-1.3.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      (sources."express-4.17.1" // {
        dependencies = [
          sources."cookie-0.4.0"
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      (sources."express-session-1.17.2" // {
        dependencies = [
          sources."cookie-0.4.1"
          sources."debug-2.6.9"
          sources."depd-2.0.0"
          sources."ms-2.0.0"
          sources."safe-buffer-5.2.1"
        ];
      })
      (sources."finalhandler-1.1.2" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      sources."forwarded-0.1.2"
      sources."fresh-0.5.2"
      sources."fs-minipass-2.1.0"
      sources."fs.realpath-1.0.0"
      sources."gauge-2.7.4"
      sources."glob-7.1.7"
      sources."graceful-readlink-1.0.1"
      (sources."has-binary-0.1.7" // {
        dependencies = [
          sources."isarray-0.0.1"
        ];
      })
      sources."has-cors-1.1.0"
      sources."has-unicode-2.0.1"
      (sources."http-errors-1.7.2" // {
        dependencies = [
          sources."inherits-2.0.3"
        ];
      })
      sources."https-proxy-agent-5.0.0"
      sources."iconv-lite-0.4.24"
      sources."indexof-0.0.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ipaddr.js-1.9.1"
      sources."is-buffer-1.1.6"
      sources."is-fullwidth-code-point-1.0.0"
      sources."is-promise-2.2.2"
      sources."isarray-1.0.0"
      (sources."jade-1.11.0" // {
        dependencies = [
          sources."mkdirp-0.5.5"
        ];
      })
      sources."json3-3.3.2"
      sources."jstransformer-0.0.2"
      sources."kareem-2.3.2"
      sources."kind-of-3.2.2"
      sources."lazy-cache-1.0.4"
      sources."longest-1.0.1"
      sources."lru-cache-6.0.0"
      (sources."make-dir-3.1.0" // {
        dependencies = [
          sources."semver-6.3.0"
        ];
      })
      sources."media-typer-0.3.0"
      sources."memory-pager-1.5.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."mime-1.6.0"
      sources."mime-db-1.47.0"
      sources."mime-types-2.1.30"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."minipass-3.1.3"
      sources."minizlib-2.1.2"
      sources."mkdirp-1.0.4"
      sources."mongodb-3.6.6"
      (sources."mongoose-5.12.10" // {
        dependencies = [
          sources."safe-buffer-5.2.1"
        ];
      })
      sources."mongoose-legacy-pluralize-1.0.2"
      sources."mpath-0.8.3"
      (sources."mquery-3.2.5" // {
        dependencies = [
          sources."debug-3.1.0"
          sources."ms-2.0.0"
        ];
      })
      sources."ms-2.1.2"
      sources."negotiator-0.6.2"
      sources."node-addon-api-3.2.0"
      sources."node-fetch-2.6.1"
      sources."nopt-5.0.0"
      sources."npmlog-4.1.2"
      sources."number-is-nan-1.0.1"
      sources."object-assign-4.1.1"
      sources."object-component-0.0.3"
      sources."on-finished-2.3.0"
      sources."on-headers-1.0.2"
      sources."once-1.4.0"
      sources."optimist-0.3.7"
      sources."optional-require-1.0.3"
      sources."options-0.0.6"
      sources."parsejson-0.0.3"
      sources."parseqs-0.0.5"
      sources."parseuri-0.0.5"
      sources."parseurl-1.3.3"
      sources."passport-0.4.1"
      sources."passport-local-1.0.0"
      sources."passport-strategy-1.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-to-regexp-0.1.7"
      sources."pause-0.0.1"
      sources."process-nextick-args-2.0.1"
      sources."promise-6.1.0"
      sources."proxy-addr-2.0.6"
      sources."qs-6.7.0"
      sources."random-bytes-1.0.0"
      sources."range-parser-1.2.1"
      sources."raw-body-2.4.0"
      sources."readable-stream-2.3.7"
      sources."regexp-clone-1.0.0"
      sources."repeat-string-1.6.1"
      sources."right-align-0.1.3"
      sources."rimraf-3.0.2"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."saslprep-1.0.3"
      sources."semver-7.3.5"
      (sources."send-0.17.1" // {
        dependencies = [
          (sources."debug-2.6.9" // {
            dependencies = [
              sources."ms-2.0.0"
            ];
          })
          sources."ms-2.1.1"
        ];
      })
      sources."serve-static-1.14.1"
      sources."set-blocking-2.0.0"
      sources."setprototypeof-1.1.1"
      sources."sift-13.5.2"
      sources."signal-exit-3.0.3"
      sources."sliced-1.0.1"
      (sources."socket.io-1.7.4" // {
        dependencies = [
          sources."debug-2.3.3"
          sources."ms-0.7.2"
          sources."object-assign-4.1.0"
        ];
      })
      (sources."socket.io-adapter-0.5.0" // {
        dependencies = [
          sources."debug-2.3.3"
          sources."ms-0.7.2"
        ];
      })
      (sources."socket.io-client-1.7.4" // {
        dependencies = [
          sources."debug-2.3.3"
          sources."ms-0.7.2"
        ];
      })
      (sources."socket.io-parser-2.3.1" // {
        dependencies = [
          sources."component-emitter-1.1.2"
          sources."debug-2.2.0"
          sources."isarray-0.0.1"
          sources."ms-0.7.1"
        ];
      })
      sources."source-map-0.4.4"
      sources."sparse-bitfield-3.0.3"
      sources."statuses-1.5.0"
      sources."string-width-1.0.2"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-3.0.1"
      sources."tar-6.1.0"
      sources."to-array-0.1.4"
      sources."toidentifier-1.0.0"
      (sources."transformers-2.1.0" // {
        dependencies = [
          sources."is-promise-1.0.1"
          sources."promise-2.0.0"
          sources."source-map-0.1.43"
          sources."uglify-js-2.2.5"
        ];
      })
      sources."type-is-1.6.18"
      (sources."uglify-js-2.8.29" // {
        dependencies = [
          sources."source-map-0.5.7"
        ];
      })
      sources."uglify-to-browserify-1.0.2"
      sources."uid-safe-2.1.5"
      sources."ultron-1.0.2"
      sources."unpipe-1.0.0"
      sources."util-deprecate-1.0.2"
      sources."utils-merge-1.0.1"
      sources."vary-1.1.2"
      sources."void-elements-2.0.1"
      sources."wide-align-1.1.3"
      sources."window-size-0.1.0"
      (sources."with-4.0.3" // {
        dependencies = [
          sources."acorn-1.2.2"
        ];
      })
      sources."wordwrap-0.0.3"
      sources."wrappy-1.0.2"
      sources."ws-1.1.5"
      sources."wtf-8-1.0.0"
      sources."xmlhttprequest-ssl-1.5.3"
      sources."yallist-4.0.0"
      sources."yargs-3.10.0"
      sources."yeast-0.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}